//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillEntity()
        {
            this.CreditOrDebitNote = new HashSet<CreditOrDebitNoteEntity>();
            this.CreditOrDebitNote1 = new HashSet<CreditOrDebitNoteEntity>();
        }
    
        public long BillId { get; set; }
        public System.DateTime EmissionDate { get; set; }
        public string Status { get; set; }
        public long UserId_FK { get; set; }
        public string PurchaseOrderCode { get; set; }
        public System.DateTime LastSendDate { get; set; }
        public decimal TotalAfterDiscount { get; set; }
        public decimal TaxesToPay { get; set; }
        public decimal SubTotalProducts { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal TotalToPay { get; set; }
        public long ClientId_FK { get; set; }
        public string XMLSendedToHacienda { get; set; }
        public string XMLReceivedFromHacienda { get; set; }
        public string SoldProductsJSON { get; set; }
        public int HaciendaFailCounter { get; set; }
        public string DocumentKey { get; set; }
        public long ConsecutiveNumber { get; set; }
        public string SellCondition { get; set; }
        public string CreditTerm { get; set; }
        public string PaymentMethod { get; set; }
        public string DiscountNature { get; set; }
        public string TaxCode { get; set; }
        public bool HaveExoneration { get; set; }
        public Nullable<long> ExonerationId_FK { get; set; }
        public decimal ExonerationAmount { get; set; }
        public string Observation { get; set; }
        public string SystemMesagges { get; set; }
        public string ReasonPhrasePOSTHacienda { get; set; }
        public string ReasonPhraseGETHacienda { get; set; }
        public string StatusCodePOSTHacienda { get; set; }
        public string ReferenceDocumentType { get; set; }
        public string StatusCodeGETHacienda { get; set; }
    
        public virtual ClientEntity Client { get; set; }
        public virtual ExonerationEntity Exoneration { get; set; }
        public virtual PaymentMethodTypeEntity PaymentMethodType { get; set; }
        public virtual ReferenceDocumentTypeEntity ReferenceDocumentType1 { get; set; }
        public virtual SellConditionsTypeEntity SellConditionsType { get; set; }
        public virtual TaxesTypeEntity TaxesType { get; set; }
        public virtual UserEntity User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditOrDebitNoteEntity> CreditOrDebitNote { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditOrDebitNoteEntity> CreditOrDebitNote1 { get; set; }
    }
}
