//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CantonTypeEntity
    {
        public int CantonTypeId { get; set; }
        public string CantonName { get; set; }
        public string CantonTypeCode { get; set; }
    }
}
