//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_barrio
    {
        public int pai_id { get; set; }
        public int prov_id { get; set; }
        public int cant_id { get; set; }
        public int dist_id { get; set; }
        public int barr_id { get; set; }
        public string barr_titulo { get; set; }
    
        public virtual cfg_distrito cfg_distrito { get; set; }
    }
}
