//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_canton
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cfg_canton()
        {
            this.cfg_distrito = new HashSet<cfg_distrito>();
        }
    
        public int pai_id { get; set; }
        public int prov_id { get; set; }
        public int cant_id { get; set; }
        public string cant_titulo { get; set; }
    
        public virtual cfg_provincia cfg_provincia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cfg_distrito> cfg_distrito { get; set; }
    }
}
