//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cfg_distrito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cfg_distrito()
        {
            this.cfg_barrio = new HashSet<cfg_barrio>();
        }
    
        public int pai_id { get; set; }
        public int prov_id { get; set; }
        public int cant_id { get; set; }
        public int dist_id { get; set; }
        public string dist_titulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cfg_barrio> cfg_barrio { get; set; }
        public virtual cfg_canton cfg_canton { get; set; }
    }
}
