//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExonerationEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExonerationEntity()
        {
            this.Bill = new HashSet<BillEntity>();
        }
    
        public long ExonerationId { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public string InstitutionName { get; set; }
        public System.DateTime EmissionDate { get; set; }
        public decimal TaxAmount { get; set; }
        public int PurchasePercentaje { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillEntity> Bill { get; set; }
        public virtual ExonerationAuthorizationDocumentTypeEntity ExonerationAuthorizationDocumentType { get; set; }
    }
}
