//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductEntity()
        {
            this.ProductsByClient = new HashSet<ProductsByClientEntity>();
        }
    
        public long ProductId { get; set; }
        public long UserId_FK { get; set; }
        public decimal Price { get; set; }
        public string MeasurementUnit { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public string CurrencyType { get; set; }
        public string BarCode { get; set; }
        public string ProductType { get; set; }
        public string ProductCode { get; set; }
        public string MeasurementUnitType { get; set; }
    
        public virtual CurrencyTypeEntity CurrencyType1 { get; set; }
        public virtual UserEntity User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsByClientEntity> ProductsByClient { get; set; }
    }
}
