//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsByClientEntity
    {
        public long ProductsByClientId { get; set; }
        public long ProductId_FK { get; set; }
        public long ClientId_FK { get; set; }
    
        public virtual ClientEntity Client { get; set; }
        public virtual ProductEntity Product { get; set; }
    }
}
