//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvinciaTypeEntity
    {
        public int ProvinciaTypeId { get; set; }
        public string ProvinciaName { get; set; }
        public string ProvinciaTypeCode { get; set; }
    }
}
