//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Goval.FacturaDigital.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserEntity()
        {
            this.AppConfiguration = new HashSet<AppConfigurationEntity>();
            this.Bill = new HashSet<BillEntity>();
            this.Client = new HashSet<ClientEntity>();
            this.Product = new HashSet<ProductEntity>();
        }
    
        public long UserId { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
        public string Email { get; set; }
        public string UserLegalNumber { get; set; }
        public string HaciendaUsername { get; set; }
        public string HaciendaPassword { get; set; }
        public string HaciendaCryptographicPIN { get; set; }
        public byte[] HaciendaCryptographicFile { get; set; }
        public string HaciendaCryptographicFileName { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public bool HaciendaUserValidation { get; set; }
        public string IdentificationType { get; set; }
        public string ComercialName { get; set; }
        public string ProvinciaCode { get; set; }
        public string CantonCode { get; set; }
        public string DistritoCode { get; set; }
        public string BarrioCode { get; set; }
        public string LocationDescription { get; set; }
        public string PhoneNumberCountryCode { get; set; }
        public string FaxCountryCode { get; set; }
        public string Fax { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppConfigurationEntity> AppConfiguration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BillEntity> Bill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientEntity> Client { get; set; }
        public virtual IdentificationTypeEntity IdentificationType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductEntity> Product { get; set; }
    }
}
