'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'

Namespace BitOne.FE.EN.MensajeReceptor

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor", IsNullable:=False)> _
    Partial Public Class MensajeReceptor

        Private claveField As String

        Private numeroCedulaEmisorField As String

        Private fechaEmisionDocField As Date

        Private mensajeField As MensajeReceptorMensaje

        Private detalleMensajeField As String

        Private montoTotalImpuestoField As Decimal

        Private montoTotalImpuestoFieldSpecified As Boolean

        Private totalFacturaField As Decimal

        Private numeroCedulaReceptorField As String

        Private numeroConsecutivoReceptorField As String

        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set(value As String)
                Me.claveField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroCedulaEmisor() As String
            Get
                Return Me.numeroCedulaEmisorField
            End Get
            Set(value As String)
                Me.numeroCedulaEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property FechaEmisionDoc() As Date
            Get
                Return Me.fechaEmisionDocField
            End Get
            Set(value As Date)
                Me.fechaEmisionDocField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Mensaje() As MensajeReceptorMensaje
            Get
                Return Me.mensajeField
            End Get
            Set(value As MensajeReceptorMensaje)
                Me.mensajeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DetalleMensaje() As String
            Get
                Return Me.detalleMensajeField
            End Get
            Set(value As String)
                Me.detalleMensajeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MontoTotalImpuesto() As Decimal
            Get
                Return Me.montoTotalImpuestoField
            End Get
            Set(value As Decimal)
                Me.montoTotalImpuestoField = Value
            End Set
        End Property

        ' '''<remarks/>
        '<System.Xml.Serialization.XmlIgnoreAttribute()> _
        'Public Property MontoTotalImpuestoSpecified() As Boolean
        '    Get
        '        Return Me.montoTotalImpuestoFieldSpecified
        '    End Get
        '    Set(value As Boolean)
        '        Me.montoTotalImpuestoFieldSpecified = Value
        '    End Set
        'End Property

        '''<remarks/>
        Public Property TotalFactura() As Decimal
            Get
                Return Me.totalFacturaField
            End Get
            Set(value As Decimal)
                Me.totalFacturaField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroCedulaReceptor() As String
            Get
                Return Me.numeroCedulaReceptorField
            End Get
            Set(value As String)
                Me.numeroCedulaReceptorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroConsecutivoReceptor() As String
            Get
                Return Me.numeroConsecutivoReceptorField
            End Get
            Set(value As String)
                Me.numeroConsecutivoReceptorField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeReceptor")> _
    Public Enum MensajeReceptorMensaje

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")> _
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")> _
        Item2

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3")> _
        Item3
    End Enum

End Namespace