'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'
Namespace BitOne.FE.EN.FacturaElectronica

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica", IsNullable:=False)> _
    Partial Public Class FacturaElectronica

        Private claveField As String

        Private numeroConsecutivoField As String

        Private fechaEmisionField As Date

        Private emisorField As EmisorType

        Private receptorField As ReceptorType

        Private condicionVentaField As FacturaElectronicaCondicionVenta

        Private plazoCreditoField As String

        Private medioPagoField() As FacturaElectronicaMedioPago

        Private detalleServicioField() As FacturaElectronicaLineaDetalle

        Private resumenFacturaField As FacturaElectronicaResumenFactura

        Private informacionReferenciaField() As InformacionReferencia

        Private normativaField As FacturaElectronicaNormativa

        Private otrosField As FacturaElectronicaOtros

        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set(value As String)
                Me.claveField = value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroConsecutivo() As String
            Get
                Return Me.numeroConsecutivoField
            End Get
            Set(value As String)
                Me.numeroConsecutivoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property FechaEmision() As Date
            Get
                Return Me.fechaEmisionField
            End Get
            Set(value As Date)
                Me.fechaEmisionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Emisor() As EmisorType
            Get
                Return Me.emisorField
            End Get
            Set(value As EmisorType)
                Me.emisorField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Receptor() As ReceptorType
            Get
                Return Me.receptorField
            End Get
            Set(value As ReceptorType)
                Me.receptorField = value
            End Set
        End Property

        '''<remarks/>
        Public Property CondicionVenta() As FacturaElectronicaCondicionVenta
            Get
                Return Me.condicionVentaField
            End Get
            Set(value As FacturaElectronicaCondicionVenta)
                Me.condicionVentaField = value
            End Set
        End Property

        '''<remarks/>
        Public Property PlazoCredito() As String
            Get
                Return Me.plazoCreditoField
            End Get
            Set(value As String)
                Me.plazoCreditoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("MedioPago")> _
        Public Property MedioPago() As FacturaElectronicaMedioPago()
            Get
                Return Me.medioPagoField
            End Get
            Set(value As FacturaElectronicaMedioPago())
                Me.medioPagoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("LineaDetalle", IsNullable:=False)> _
        Public Property DetalleServicio() As FacturaElectronicaLineaDetalle()
            Get
                Return Me.detalleServicioField
            End Get
            Set(value As FacturaElectronicaLineaDetalle())
                Me.detalleServicioField = value
            End Set
        End Property

        '''<remarks/>
        Public Property ResumenFactura() As FacturaElectronicaResumenFactura
            Get
                Return Me.resumenFacturaField
            End Get
            Set(value As FacturaElectronicaResumenFactura)
                Me.resumenFacturaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionReferencia")> _
        Public Property InformacionReferencia() As InformacionReferencia()
            Get
                Return Me.informacionReferenciaField
            End Get
            Set(value As InformacionReferencia())
                Me.informacionReferenciaField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Normativa() As FacturaElectronicaNormativa
            Get
                Return Me.normativaField
            End Get
            Set(value As FacturaElectronicaNormativa)
                Me.normativaField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Otros() As FacturaElectronicaOtros
            Get
                Return Me.otrosField
            End Get
            Set(value As FacturaElectronicaOtros)
                Me.otrosField = value
            End Set
        End Property
    End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class EmisorType

    '    Private nombreField As String

    '    Private identificacionField As IdentificacionType

    '    Private nombreComercialField As String

    '    Private ubicacionField As UbicacionType

    '    Private telefonoField As TelefonoType

    '    Private faxField As TelefonoType

    '    Private correoElectronicoField As String

    '    '''<remarks/>
    '    Public Property Nombre() As String
    '        Get
    '            Return Me.nombreField
    '        End Get
    '        Set(value As String)
    '            Me.nombreField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Identificacion() As IdentificacionType
    '        Get
    '            Return Me.identificacionField
    '        End Get
    '        Set(value As IdentificacionType)
    '            Me.identificacionField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property NombreComercial() As String
    '        Get
    '            Return Me.nombreComercialField
    '        End Get
    '        Set(value As String)
    '            Me.nombreComercialField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Ubicacion() As UbicacionType
    '        Get
    '            Return Me.ubicacionField
    '        End Get
    '        Set(value As UbicacionType)
    '            Me.ubicacionField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    '    Public Property Telefono() As TelefonoType
    '        Get
    '            Return Me.telefonoField
    '        End Get
    '        Set(value As TelefonoType)
    '            Me.telefonoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlElementAttribute(IsNullable:=True)> _
    '    Public Property Fax() As TelefonoType
    '        Get
    '            Return Me.faxField
    '        End Get
    '        Set(value As TelefonoType)
    '            Me.faxField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property CorreoElectronico() As String
    '        Get
    '            Return Me.correoElectronicoField
    '        End Get
    '        Set(value As String)
    '            Me.correoElectronicoField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class IdentificacionType

    '    Private tipoField As IdentificacionTypeTipo

    '    Private numeroField As String

    '    '''<remarks/>
    '    Public Property Tipo() As IdentificacionTypeTipo
    '        Get
    '            Return Me.tipoField
    '        End Get
    '        Set(value As IdentificacionTypeTipo)
    '            Me.tipoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Numero() As String
    '        Get
    '            Return Me.numeroField
    '        End Get
    '        Set(value As String)
    '            Me.numeroField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum IdentificacionTypeTipo

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("01")> _
    '    Item01

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("02")> _
    '    Item02

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("03")> _
    '    Item03

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("04")> _
    '    Item04
    'End Enum

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class ExoneracionType

    '    Private tipoDocumentoField As ExoneracionTypeTipoDocumento

    '    Private numeroDocumentoField As String

    '    Private nombreInstitucionField As String

    '    Private fechaEmisionField As Date

    '    Private montoImpuestoField As Decimal

    '    Private porcentajeCompraField As String

    '    '''<remarks/>
    '    Public Property TipoDocumento() As ExoneracionTypeTipoDocumento
    '        Get
    '            Return Me.tipoDocumentoField
    '        End Get
    '        Set(value As ExoneracionTypeTipoDocumento)
    '            Me.tipoDocumentoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property NumeroDocumento() As String
    '        Get
    '            Return Me.numeroDocumentoField
    '        End Get
    '        Set(value As String)
    '            Me.numeroDocumentoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property NombreInstitucion() As String
    '        Get
    '            Return Me.nombreInstitucionField
    '        End Get
    '        Set(value As String)
    '            Me.nombreInstitucionField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property FechaEmision() As Date
    '        Get
    '            Return Me.fechaEmisionField
    '        End Get
    '        Set(value As Date)
    '            Me.fechaEmisionField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property MontoImpuesto() As Decimal
    '        Get
    '            Return Me.montoImpuestoField
    '        End Get
    '        Set(value As Decimal)
    '            Me.montoImpuestoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
    '    Public Property PorcentajeCompra() As String
    '        Get
    '            Return Me.porcentajeCompraField
    '        End Get
    '        Set(value As String)
    '            Me.porcentajeCompraField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum ExoneracionTypeTipoDocumento

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("01")> _
    '    Item01

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("02")> _
    '    Item02

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("03")> _
    '    Item03

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("04")> _
    '    Item04

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("05")> _
    '    Item05

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("99")> _
    '    Item99
    'End Enum

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class ImpuestoType

    '    Private codigoField As ImpuestoTypeCodigo

    '    Private tarifaField As Decimal

    '    Private montoField As Decimal

    '    Private exoneracionField As ExoneracionType

    '    '''<remarks/>
    '    Public Property Codigo() As ImpuestoTypeCodigo
    '        Get
    '            Return Me.codigoField
    '        End Get
    '        Set(value As ImpuestoTypeCodigo)
    '            Me.codigoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Tarifa() As Decimal
    '        Get
    '            Return Me.tarifaField
    '        End Get
    '        Set(value As Decimal)
    '            Me.tarifaField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Monto() As Decimal
    '        Get
    '            Return Me.montoField
    '        End Get
    '        Set(value As Decimal)
    '            Me.montoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Exoneracion() As ExoneracionType
    '        Get
    '            Return Me.exoneracionField
    '        End Get
    '        Set(value As ExoneracionType)
    '            Me.exoneracionField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum ImpuestoTypeCodigo

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("01")> _
    '    Item01

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("02")> _
    '    Item02

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("03")> _
    '    Item03

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("04")> _
    '    Item04

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("05")> _
    '    Item05

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("06")> _
    '    Item06

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("07")> _
    '    Item07

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("08")> _
    '    Item08

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("09")> _
    '    Item09

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("10")> _
    '    Item10

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("11")> _
    '    Item11

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("12")> _
    '    Item12

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("98")> _
    '    Item98

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("99")> _
    '    Item99
    'End Enum

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class CodigoType

    '    Private tipoField As CodigoTypeTipo

    '    Private codigoField As String

    '    '''<remarks/>
    '    Public Property Tipo() As CodigoTypeTipo
    '        Get
    '            Return Me.tipoField
    '        End Get
    '        Set(value As CodigoTypeTipo)
    '            Me.tipoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Codigo() As String
    '        Get
    '            Return Me.codigoField
    '        End Get
    '        Set(value As String)
    '            Me.codigoField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum CodigoTypeTipo

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("01")> _
    '    Item01

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("02")> _
    '    Item02

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("03")> _
    '    Item03

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("04")> _
    '    Item04

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("99")> _
    '    Item99
    'End Enum

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class ReceptorType

    '    Private nombreField As String

    '    Private identificacionField As IdentificacionType

    '    Private identificacionExtranjeroField As String

    '    Private nombreComercialField As String

    '    Private ubicacionField As UbicacionType

    '    Private telefonoField As TelefonoType

    '    Private faxField As TelefonoType

    '    Private correoElectronicoField As String

    '    '''<remarks/>
    '    Public Property Nombre() As String
    '        Get
    '            Return Me.nombreField
    '        End Get
    '        Set(value As String)
    '            Me.nombreField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Identificacion() As IdentificacionType
    '        Get
    '            Return Me.identificacionField
    '        End Get
    '        Set(value As IdentificacionType)
    '            Me.identificacionField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property IdentificacionExtranjero() As String
    '        Get
    '            Return Me.identificacionExtranjeroField
    '        End Get
    '        Set(value As String)
    '            Me.identificacionExtranjeroField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property NombreComercial() As String
    '        Get
    '            Return Me.nombreComercialField
    '        End Get
    '        Set(value As String)
    '            Me.nombreComercialField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Ubicacion() As UbicacionType
    '        Get
    '            Return Me.ubicacionField
    '        End Get
    '        Set(value As UbicacionType)
    '            Me.ubicacionField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Telefono() As TelefonoType
    '        Get
    '            Return Me.telefonoField
    '        End Get
    '        Set(value As TelefonoType)
    '            Me.telefonoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Fax() As TelefonoType
    '        Get
    '            Return Me.faxField
    '        End Get
    '        Set(value As TelefonoType)
    '            Me.faxField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property CorreoElectronico() As String
    '        Get
    '            Return Me.correoElectronicoField
    '        End Get
    '        Set(value As String)
    '            Me.correoElectronicoField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class UbicacionType

    '    Private provinciaField As String

    '    Private cantonField As String

    '    Private distritoField As String

    '    Private barrioField As String

    '    Private otrasSenasField As String

    '    '''<remarks/>
    '    Public Property Provincia() As String
    '        Get
    '            Return Me.provinciaField
    '        End Get
    '        Set(value As String)
    '            Me.provinciaField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Canton() As String
    '        Get
    '            Return Me.cantonField
    '        End Get
    '        Set(value As String)
    '            Me.cantonField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Distrito() As String
    '        Get
    '            Return Me.distritoField
    '        End Get
    '        Set(value As String)
    '            Me.distritoField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property Barrio() As String
    '        Get
    '            Return Me.barrioField
    '        End Get
    '        Set(value As String)
    '            Me.barrioField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    Public Property OtrasSenas() As String
    '        Get
    '            Return Me.otrasSenasField
    '        End Get
    '        Set(value As String)
    '            Me.otrasSenasField = value
    '        End Set
    '    End Property
    'End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Diagnostics.DebuggerStepThroughAttribute(), _
    ' System.ComponentModel.DesignerCategoryAttribute("code"), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Partial Public Class TelefonoType

    '    Private codigoPaisField As String

    '    Private numTelefonoField As String

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
    '    Public Property CodigoPais() As String
    '        Get
    '            Return Me.codigoPaisField
    '        End Get
    '        Set(value As String)
    '            Me.codigoPaisField = value
    '        End Set
    '    End Property

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlElementAttribute(DataType:="integer")> _
    '    Public Property NumTelefono() As String
    '        Get
    '            Return Me.numTelefonoField
    '        End Get
    '        Set(value As String)
    '            Me.numTelefonoField = value
    '        End Set
    '    End Property
    'End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Public Enum FacturaElectronicaCondicionVenta

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("01")> _
        Item01

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("02")> _
        Item02

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("03")> _
        Item03

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("04")> _
        Item04

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("05")> _
        Item05

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("06")> _
        Item06

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("99")> _
        Item99
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Public Enum FacturaElectronicaMedioPago

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("01")> _
        Item01

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("02")> _
        Item02

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("03")> _
        Item03

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("04")> _
        Item04

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("05")> _
        Item05

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("99")> _
        Item99
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Partial Public Class FacturaElectronicaLineaDetalle

        Private numeroLineaField As String

        Private codigoField() As CodigoType

        Private cantidadField As Decimal

        Private unidadMedidaField As UnidadMedidaType

        Private unidadMedidaComercialField As String

        Private detalleField As String

        Private precioUnitarioField As Decimal

        Private montoTotalField As Decimal

        Private montoDescuentoField As Decimal

        Private montoDescuentoFieldSpecified As Boolean

        Private naturalezaDescuentoField As String

        Private subTotalField As Decimal

        Private impuestoField() As ImpuestoType

        Private montoTotalLineaField As Decimal

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="positiveInteger")> _
        Public Property NumeroLinea() As String
            Get
                Return Me.numeroLineaField
            End Get
            Set(value As String)
                Me.numeroLineaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Codigo")> _
        Public Property Codigo() As CodigoType()
            Get
                Return Me.codigoField
            End Get
            Set(value As CodigoType())
                Me.codigoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Cantidad() As Decimal
            Get
                Return Me.cantidadField
            End Get
            Set(value As Decimal)
                Me.cantidadField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UnidadMedida() As UnidadMedidaType
            Get
                Return Me.unidadMedidaField
            End Get
            Set(value As UnidadMedidaType)
                Me.unidadMedidaField = value
            End Set
        End Property

        '''<remarks/>
        Public Property UnidadMedidaComercial() As String
            Get
                Return Me.unidadMedidaComercialField
            End Get
            Set(value As String)
                Me.unidadMedidaComercialField = value
            End Set
        End Property

        '''<remarks/>
        Public Property Detalle() As String
            Get
                Return Me.detalleField
            End Get
            Set(value As String)
                Me.detalleField = value
            End Set
        End Property

        '''<remarks/>
        Public Property PrecioUnitario() As Decimal
            Get
                Return Me.precioUnitarioField
            End Get
            Set(value As Decimal)
                Me.precioUnitarioField = value
            End Set
        End Property

        '''<remarks/>
        Public Property MontoTotal() As Decimal
            Get
                Return Me.montoTotalField
            End Get
            Set(value As Decimal)
                Me.montoTotalField = value
            End Set
        End Property

        '''<remarks/>
        Public Property MontoDescuento() As Decimal
            Get
                Return Me.montoDescuentoField
            End Get
            Set(value As Decimal)
                Me.montoDescuentoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property MontoDescuentoSpecified() As Boolean
            Get
                Return Me.montoDescuentoFieldSpecified
            End Get
            Set(value As Boolean)
                Me.montoDescuentoFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property NaturalezaDescuento() As String
            Get
                Return Me.naturalezaDescuentoField
            End Get
            Set(value As String)
                Me.naturalezaDescuentoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property SubTotal() As Decimal
            Get
                Return Me.subTotalField
            End Get
            Set(value As Decimal)
                Me.subTotalField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Impuesto")> _
        Public Property Impuesto() As ImpuestoType()
            Get
                Return Me.impuestoField
            End Get
            Set(value As ImpuestoType())
                Me.impuestoField = value
            End Set
        End Property

        '''<remarks/>
        Public Property MontoTotalLinea() As Decimal
            Get
                Return Me.montoTotalLineaField
            End Get
            Set(value As Decimal)
                Me.montoTotalLineaField = value
            End Set
        End Property
    End Class

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum UnidadMedidaType

    '    '''<remarks/>
    '    Sp

    '    '''<remarks/>
    '    m

    '    '''<remarks/>
    '    kg

    '    '''<remarks/>
    '    s

    '    '''<remarks/>
    '    A

    '    '''<remarks/>
    '    K

    '    '''<remarks/>
    '    mol

    '    '''<remarks/>
    '    cd

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("mÂ²")> _
    '    mÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("mÂ³")> _
    '    mÂ1

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("m/s")> _
    '    ms

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("m/sÂ²")> _
    '    msÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("1/m")> _
    '    Item1m

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("kg/mÂ³")> _
    '    kgmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("A/mÂ²")> _
    '    AmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("A/m")> _
    '    Am

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("mol/mÂ³")> _
    '    molmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("cd/mÂ²")> _
    '    cdmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("1")> _
    '    Item1

    '    '''<remarks/>
    '    rad

    '    '''<remarks/>
    '    sr

    '    '''<remarks/>
    '    Hz

    '    '''<remarks/>
    '    N

    '    '''<remarks/>
    '    Pa

    '    '''<remarks/>
    '    J

    '    '''<remarks/>
    '    W

    '    '''<remarks/>
    '    C

    '    '''<remarks/>
    '    V

    '    '''<remarks/>
    '    F

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("â„¦")> _
    '    â

    '    '''<remarks/>
    '    Wb

    '    '''<remarks/>
    '    T

    '    '''<remarks/>
    '    H

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("Â°C")> _
    '    ÂC

    '    '''<remarks/>
    '    lm

    '    '''<remarks/>
    '    lx

    '    '''<remarks/>
    '    Bq

    '    '''<remarks/>
    '    Gy

    '    '''<remarks/>
    '    Sv

    '    '''<remarks/>
    '    kat

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("PaÂ·s")> _
    '    PaÂs

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("NÂ·m")> _
    '    NÂm

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("N/m")> _
    '    Nm

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("rad/s")> _
    '    rads

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("rad/sÂ²")> _
    '    radsÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("W/mÂ²")> _
    '    WmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("J/K")> _
    '    JK

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("J/(kgÂ·K)")> _
    '    JkgÂK

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("J/kg")> _
    '    Jkg

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("W/(mÂ·K)")> _
    '    WmÂK

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("J/mÂ³")> _
    '    JmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("V/m")> _
    '    Vm

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("C/mÂ³")> _
    '    CmÂ

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("C/mÂ²")> _
    '    CmÂ1

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("F/m")> _
    '    Fm

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("H/m")> _
    '    Hm

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("J/mol")> _
    '    Jmol

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("J/(molÂ·K)")> _
    '    JmolÂK

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("C/kg")> _
    '    Ckg

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("Gy/s")> _
    '    Gys

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("W/sr")> _
    '    Wsr

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("W/(mÂ²Â·sr)")> _
    '    WmÂÂsr

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("kat/mÂ³")> _
    '    katmÂ

    '    '''<remarks/>
    '    min


    '    '''<remarks/>
    '    d

    '    '''<remarks/>
    '    Âº

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("Â´Â´")> _
    '    ÂÂ

    '    '''<remarks/>
    '    L

    '    '''<remarks/>
    '    Np

    '    '''<remarks/>
    '    B

    '    '''<remarks/>
    '    eV

    '    '''<remarks/>
    '    u

    '    '''<remarks/>
    '    ua

    '    '''<remarks/>
    '    Unid

    '    '''<remarks/>
    '    Gal

    '    '''<remarks/>
    '    g

    '    '''<remarks/>
    '    Km

    '    '''<remarks/>
    '    ln

    '    '''<remarks/>
    '    cm

    '    '''<remarks/>
    '    mL

    '    '''<remarks/>
    '    mm

    '    '''<remarks/>
    '    Oz

    '    '''<remarks/>
    '    Otros
    'End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Partial Public Class FacturaElectronicaResumenFactura

        Private codigoMonedaField As FacturaElectronicaResumenFacturaCodigoMoneda

        Private codigoMonedaFieldSpecified As Boolean

        Private tipoCambioField As Decimal

        Private tipoCambioFieldSpecified As Boolean

        Private totalServGravadosField As Decimal

        Private totalServGravadosFieldSpecified As Boolean

        Private totalServExentosField As Decimal

        Private totalServExentosFieldSpecified As Boolean

        Private totalMercanciasGravadasField As Decimal

        Private totalMercanciasGravadasFieldSpecified As Boolean

        Private totalMercanciasExentasField As Decimal

        Private totalMercanciasExentasFieldSpecified As Boolean

        Private totalGravadoField As Decimal

        Private totalGravadoFieldSpecified As Boolean

        Private totalExentoField As Decimal

        Private totalExentoFieldSpecified As Boolean

        Private totalVentaField As Decimal

        Private totalDescuentosField As Decimal

        Private totalDescuentosFieldSpecified As Boolean

        Private totalVentaNetaField As Decimal

        Private totalImpuestoField As Decimal

        Private totalImpuestoFieldSpecified As Boolean

        Private totalComprobanteField As Decimal

        '''<remarks/>
        Public Property CodigoMoneda() As FacturaElectronicaResumenFacturaCodigoMoneda
            Get
                Return Me.codigoMonedaField
            End Get
            Set(value As FacturaElectronicaResumenFacturaCodigoMoneda)
                Me.codigoMonedaField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property CodigoMonedaSpecified() As Boolean
            Get
                Return Me.codigoMonedaFieldSpecified
            End Get
            Set(value As Boolean)
                Me.codigoMonedaFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoCambio() As Decimal
            Get
                Return Me.tipoCambioField
            End Get
            Set(value As Decimal)
                Me.tipoCambioField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TipoCambioSpecified() As Boolean
            Get
                Return Me.tipoCambioFieldSpecified
            End Get
            Set(value As Boolean)
                Me.tipoCambioFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalServGravados() As Decimal
            Get
                Return Me.totalServGravadosField
            End Get
            Set(value As Decimal)
                Me.totalServGravadosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalServGravadosSpecified() As Boolean
            Get
                Return Me.totalServGravadosFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalServGravadosFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalServExentos() As Decimal
            Get
                Return Me.totalServExentosField
            End Get
            Set(value As Decimal)
                Me.totalServExentosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalServExentosSpecified() As Boolean
            Get
                Return Me.totalServExentosFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalServExentosFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalMercanciasGravadas() As Decimal
            Get
                Return Me.totalMercanciasGravadasField
            End Get
            Set(value As Decimal)
                Me.totalMercanciasGravadasField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalMercanciasGravadasSpecified() As Boolean
            Get
                Return Me.totalMercanciasGravadasFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalMercanciasGravadasFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalMercanciasExentas() As Decimal
            Get
                Return Me.totalMercanciasExentasField
            End Get
            Set(value As Decimal)
                Me.totalMercanciasExentasField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalMercanciasExentasSpecified() As Boolean
            Get
                Return Me.totalMercanciasExentasFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalMercanciasExentasFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalGravado() As Decimal
            Get
                Return Me.totalGravadoField
            End Get
            Set(value As Decimal)
                Me.totalGravadoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalGravadoSpecified() As Boolean
            Get
                Return Me.totalGravadoFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalGravadoFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalExento() As Decimal
            Get
                Return Me.totalExentoField
            End Get
            Set(value As Decimal)
                Me.totalExentoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalExentoSpecified() As Boolean
            Get
                Return Me.totalExentoFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalExentoFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalVenta() As Decimal
            Get
                Return Me.totalVentaField
            End Get
            Set(value As Decimal)
                Me.totalVentaField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalDescuentos() As Decimal
            Get
                Return Me.totalDescuentosField
            End Get
            Set(value As Decimal)
                Me.totalDescuentosField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalDescuentosSpecified() As Boolean
            Get
                Return Me.totalDescuentosFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalDescuentosFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalVentaNeta() As Decimal
            Get
                Return Me.totalVentaNetaField
            End Get
            Set(value As Decimal)
                Me.totalVentaNetaField = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalImpuesto() As Decimal
            Get
                Return Me.totalImpuestoField
            End Get
            Set(value As Decimal)
                Me.totalImpuestoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TotalImpuestoSpecified() As Boolean
            Get
                Return Me.totalImpuestoFieldSpecified
            End Get
            Set(value As Boolean)
                Me.totalImpuestoFieldSpecified = value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalComprobante() As Decimal
            Get
                Return Me.totalComprobanteField
            End Get
            Set(value As Decimal)
                Me.totalComprobanteField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Public Enum FacturaElectronicaResumenFacturaCodigoMoneda

        '''<remarks/>
        AED

        '''<remarks/>
        AFN

        '''<remarks/>
        ALL

        '''<remarks/>
        AMD

        '''<remarks/>
        ANG

        '''<remarks/>
        AOA

        '''<remarks/>
        ARS

        '''<remarks/>
        AUD

        '''<remarks/>
        AWG

        '''<remarks/>
        AZN

        '''<remarks/>
        BAM

        '''<remarks/>
        BBD

        '''<remarks/>
        BDT

        '''<remarks/>
        BGN

        '''<remarks/>
        BHD

        '''<remarks/>
        BIF

        '''<remarks/>
        BMD

        '''<remarks/>
        BND

        '''<remarks/>
        BOB

        '''<remarks/>
        BOV

        '''<remarks/>
        BRL

        '''<remarks/>
        BSD

        '''<remarks/>
        BTN

        '''<remarks/>
        BWP

        '''<remarks/>
        BYR

        '''<remarks/>
        BZD

        '''<remarks/>
        CAD

        '''<remarks/>
        CDF

        '''<remarks/>
        CHE

        '''<remarks/>
        CHF

        '''<remarks/>
        CHW

        '''<remarks/>
        CLF

        '''<remarks/>
        CLP

        '''<remarks/>
        CNY

        '''<remarks/>
        COP

        '''<remarks/>
        COU

        '''<remarks/>
        CRC

        '''<remarks/>
        CUC

        '''<remarks/>
        CUP

        '''<remarks/>
        CVE

        '''<remarks/>
        CZK

        '''<remarks/>
        DJF

        '''<remarks/>
        DKK

        '''<remarks/>
        DOP

        '''<remarks/>
        DZD

        '''<remarks/>
        EGP

        '''<remarks/>
        ERN

        '''<remarks/>
        ETB

        '''<remarks/>
        EUR

        '''<remarks/>
        FJD

        '''<remarks/>
        FKP

        '''<remarks/>
        GBP

        '''<remarks/>
        GEL

        '''<remarks/>
        GHS

        '''<remarks/>
        GIP

        '''<remarks/>
        GMD

        '''<remarks/>
        GNF

        '''<remarks/>
        GTQ

        '''<remarks/>
        GYD

        '''<remarks/>
        HKD

        '''<remarks/>
        HNL

        '''<remarks/>
        HRK

        '''<remarks/>
        HTG

        '''<remarks/>
        HUF

        '''<remarks/>
        IDR

        '''<remarks/>
        ILS

        '''<remarks/>
        INR

        '''<remarks/>
        IQD

        '''<remarks/>
        IRR

        '''<remarks/>
        ISK

        '''<remarks/>
        JMD

        '''<remarks/>
        JOD

        '''<remarks/>
        JPY

        '''<remarks/>
        KES

        '''<remarks/>
        KGS

        '''<remarks/>
        KHR

        '''<remarks/>
        KMF

        '''<remarks/>
        KPW

        '''<remarks/>
        KRW

        '''<remarks/>
        KWD

        '''<remarks/>
        KYD

        '''<remarks/>
        KZT

        '''<remarks/>
        LAK

        '''<remarks/>
        LBP

        '''<remarks/>
        LKR

        '''<remarks/>
        LRD

        '''<remarks/>
        LSL

        '''<remarks/>
        LYD

        '''<remarks/>
        MAD

        '''<remarks/>
        MDL

        '''<remarks/>
        MGA

        '''<remarks/>
        MKD

        '''<remarks/>
        MMK

        '''<remarks/>
        MNT

        '''<remarks/>
        MOP

        '''<remarks/>
        MRO

        '''<remarks/>
        MUR

        '''<remarks/>
        MVR

        '''<remarks/>
        MWK

        '''<remarks/>
        MXN

        '''<remarks/>
        MXV

        '''<remarks/>
        MYR

        '''<remarks/>
        MZN

        '''<remarks/>
        NAD

        '''<remarks/>
        NGN

        '''<remarks/>
        NIO

        '''<remarks/>
        NOK

        '''<remarks/>
        NPR

        '''<remarks/>
        NZD

        '''<remarks/>
        OMR

        '''<remarks/>
        PAB

        '''<remarks/>
        PEN

        '''<remarks/>
        PGK

        '''<remarks/>
        PHP

        '''<remarks/>
        PKR

        '''<remarks/>
        PLN

        '''<remarks/>
        PYG

        '''<remarks/>
        QAR

        '''<remarks/>
        RON

        '''<remarks/>
        RSD

        '''<remarks/>
        RUB

        '''<remarks/>
        RWF

        '''<remarks/>
        SAR

        '''<remarks/>
        SBD

        '''<remarks/>
        SCR

        '''<remarks/>
        SDG

        '''<remarks/>
        SEK

        '''<remarks/>
        SGD

        '''<remarks/>
        SHP

        '''<remarks/>
        SLL

        '''<remarks/>
        SOS

        '''<remarks/>
        SRD

        '''<remarks/>
        SSP

        '''<remarks/>
        STD

        '''<remarks/>
        SVC

        '''<remarks/>
        SYP

        '''<remarks/>
        SZL

        '''<remarks/>
        THB

        '''<remarks/>
        TJS

        '''<remarks/>
        TMT

        '''<remarks/>
        TND

        '''<remarks/>
        TOP

        '''<remarks/>
        [TRY]

        '''<remarks/>
        TTD

        '''<remarks/>
        TWD

        '''<remarks/>
        TZS

        '''<remarks/>
        UAH

        '''<remarks/>
        UGX

        '''<remarks/>
        USD

        '''<remarks/>
        USN

        '''<remarks/>
        UYI

        '''<remarks/>
        UYU

        '''<remarks/>
        UZS

        '''<remarks/>
        VEF

        '''<remarks/>
        VND

        '''<remarks/>
        VUV

        '''<remarks/>
        WST

        '''<remarks/>
        XAF

        '''<remarks/>
        XAG

        '''<remarks/>
        XAU

        '''<remarks/>
        XBA

        '''<remarks/>
        XBB

        '''<remarks/>
        XBC

        '''<remarks/>
        XBD

        '''<remarks/>
        XCD

        '''<remarks/>
        XDR

        '''<remarks/>
        XOF

        '''<remarks/>
        XPD

        '''<remarks/>
        XPF

        '''<remarks/>
        XPT

        '''<remarks/>
        XSU

        '''<remarks/>
        XTS

        '''<remarks/>
        XUA

        '''<remarks/>
        XXX

        '''<remarks/>
        YER

        '''<remarks/>
        ZAR

        '''<remarks/>
        ZMW

        '''<remarks/>
        ZWL
    End Enum


    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum FacturaElectronicaInformacionReferenciaTipoDoc

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("01")> _
    '    Item01

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("02")> _
    '    Item02

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("03")> _
    '    Item03

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("04")> _
    '    Item04

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("05")> _
    '    Item05

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("06")> _
    '    Item06

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("07")> _
    '    Item07

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("08")> _
    '    Item08

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("99")> _
    '    Item99
    'End Enum

    ' '''<remarks/>
    '<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
    ' System.SerializableAttribute(), _
    ' System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    'Public Enum FacturaElectronicaInformacionReferenciaCodigo

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("01")> _
    '    Item01

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("02")> _
    '    Item02

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("03")> _
    '    Item03

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("04")> _
    '    Item04

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("05")> _
    '    Item05

    '    '''<remarks/>
    '    <System.Xml.Serialization.XmlEnumAttribute("99")> _
    '    Item99
    'End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Partial Public Class FacturaElectronicaNormativa

        Private numeroResolucionField As String

        Private fechaResolucionField As String

        '''<remarks/>
        Public Property NumeroResolucion() As String
            Get
                Return Me.numeroResolucionField
            End Get
            Set(value As String)
                Me.numeroResolucionField = value
            End Set
        End Property

        '''<remarks/>
        Public Property FechaResolucion() As String
            Get
                Return Me.fechaResolucionField
            End Get
            Set(value As String)
                Me.fechaResolucionField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Partial Public Class FacturaElectronicaOtros

        Private otroTextoField() As FacturaElectronicaOtrosOtroTexto

        Private otroContenidoField() As FacturaElectronicaOtrosOtroContenido

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OtroTexto")> _
        Public Property OtroTexto() As FacturaElectronicaOtrosOtroTexto()
            Get
                Return Me.otroTextoField
            End Get
            Set(value As FacturaElectronicaOtrosOtroTexto())
                Me.otroTextoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("OtroContenido")> _
        Public Property OtroContenido() As FacturaElectronicaOtrosOtroContenido()
            Get
                Return Me.otroContenidoField
            End Get
            Set(value As FacturaElectronicaOtrosOtroContenido())
                Me.otroContenidoField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Partial Public Class FacturaElectronicaOtrosOtroTexto

        Private codigoField As String

        Private valueField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set(value As String)
                Me.codigoField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlTextAttribute()> _
        Public Property Value() As String
            Get
                Return Me.valueField
            End Get
            Set(value As String)
                Me.valueField = value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/facturaElectronica")> _
    Partial Public Class FacturaElectronicaOtrosOtroContenido

        Private anyField As System.Xml.XmlElement

        Private codigoField As String

        '''<remarks/>
        <System.Xml.Serialization.XmlAnyElementAttribute()> _
        Public Property Any() As System.Xml.XmlElement
            Get
                Return Me.anyField
            End Get
            Set(value As System.Xml.XmlElement)
                Me.anyField = value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()> _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set(value As String)
                Me.codigoField = value
            End Set
        End Property
    End Class

End Namespace