'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'This source code was auto-generated by xsd, Version=4.0.30319.33440.
'
Namespace BitOne.FE.EN.MensajeHacienda



    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda"), _
     System.Xml.Serialization.XmlRootAttribute([Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda", IsNullable:=False)> _
    Partial Public Class MensajeHacienda

        Private claveField As String

        Private nombreEmisorField As String

        Private tipoIdentificacionEmisorField As MensajeHaciendaTipoIdentificacionEmisor

        Private numeroCedulaEmisorField As String

        Private nombreReceptorField As String

        Private tipoIdentificacionReceptorField As MensajeHaciendaTipoIdentificacionReceptor

        Private tipoIdentificacionReceptorFieldSpecified As Boolean

        Private numeroCedulaReceptorField As String

        Private mensajeField As MensajeHaciendaMensaje

        Private detalleMensajeField As String

        Private montoTotalImpuestoField As Decimal

        Private montoTotalImpuestoFieldSpecified As Boolean

        Private totalFacturaField As Decimal

        '''<remarks/>
        Public Property Clave() As String
            Get
                Return Me.claveField
            End Get
            Set(value As String)
                Me.claveField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NombreEmisor() As String
            Get
                Return Me.nombreEmisorField
            End Get
            Set(value As String)
                Me.nombreEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoIdentificacionEmisor() As MensajeHaciendaTipoIdentificacionEmisor
            Get
                Return Me.tipoIdentificacionEmisorField
            End Get
            Set(value As MensajeHaciendaTipoIdentificacionEmisor)
                Me.tipoIdentificacionEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroCedulaEmisor() As String
            Get
                Return Me.numeroCedulaEmisorField
            End Get
            Set(value As String)
                Me.numeroCedulaEmisorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NombreReceptor() As String
            Get
                Return Me.nombreReceptorField
            End Get
            Set(value As String)
                Me.nombreReceptorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TipoIdentificacionReceptor() As MensajeHaciendaTipoIdentificacionReceptor
            Get
                Return Me.tipoIdentificacionReceptorField
            End Get
            Set(value As MensajeHaciendaTipoIdentificacionReceptor)
                Me.tipoIdentificacionReceptorField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property TipoIdentificacionReceptorSpecified() As Boolean
            Get
                Return Me.tipoIdentificacionReceptorFieldSpecified
            End Get
            Set(value As Boolean)
                Me.tipoIdentificacionReceptorFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property NumeroCedulaReceptor() As String
            Get
                Return Me.numeroCedulaReceptorField
            End Get
            Set(value As String)
                Me.numeroCedulaReceptorField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property Mensaje() As MensajeHaciendaMensaje
            Get
                Return Me.mensajeField
            End Get
            Set(value As MensajeHaciendaMensaje)
                Me.mensajeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property DetalleMensaje() As String
            Get
                Return Me.detalleMensajeField
            End Get
            Set(value As String)
                Me.detalleMensajeField = Value
            End Set
        End Property

        '''<remarks/>
        Public Property MontoTotalImpuesto() As Decimal
            Get
                Return Me.montoTotalImpuestoField
            End Get
            Set(value As Decimal)
                Me.montoTotalImpuestoField = Value
            End Set
        End Property

        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()> _
        Public Property MontoTotalImpuestoSpecified() As Boolean
            Get
                Return Me.montoTotalImpuestoFieldSpecified
            End Get
            Set(value As Boolean)
                Me.montoTotalImpuestoFieldSpecified = Value
            End Set
        End Property

        '''<remarks/>
        Public Property TotalFactura() As Decimal
            Get
                Return Me.totalFacturaField
            End Get
            Set(value As Decimal)
                Me.totalFacturaField = Value
            End Set
        End Property
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")> _
    Public Enum MensajeHaciendaTipoIdentificacionEmisor

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("01")> _
        Item01

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("02")> _
        Item02

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("03")> _
        Item03

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("04")> _
        Item04
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")> _
    Public Enum MensajeHaciendaTipoIdentificacionReceptor

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("01")> _
        Item01

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("02")> _
        Item02

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("03")> _
        Item03

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("04")> _
        Item04

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("05")> _
        Item05
    End Enum

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440"), _
     System.SerializableAttribute(), _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="https://tribunet.hacienda.go.cr/docs/esquemas/2017/v4.2/mensajeHacienda")> _
    Public Enum MensajeHaciendaMensaje

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")> _
        Item1

        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3")> _
        Item3
    End Enum

End Namespace